import type { Spec, Task, Requirement, SpecMetadata } from './types.js';

/**
 * Default spec template
 */
export const DEFAULT_SPEC_TEMPLATE = `# {title}

## Overview

{description}

## Status

**Status:** {status}

## Requirements

{requirements}

## Design

{design}

## Tasks

{tasks}

## Notes

{notes}
`;

/**
 * Create a new spec from template
 */
export function createSpecFromTemplate(
  id: string,
  title: string,
  description: string,
  template: string = DEFAULT_SPEC_TEMPLATE
): Spec {
  const now = new Date();
  
  return {
    id,
    title,
    description,
    status: 'draft',
    createdAt: now,
    updatedAt: now,
    path: `./specs/${id}`,
    requirements: [],
    tasks: [],
  };
}

/**
 * Generate markdown from spec
 */
export function specToMarkdown(spec: Spec): string {
  const lines: string[] = [
    `# ${spec.title}`,
    '',
    `## Overview`,
    '',
    spec.description,
    '',
    `## Status`,
    '',
    `**Status:** ${spec.status}`,
    '',
  ];
  
  if (spec.requirements && spec.requirements.length > 0) {
    lines.push(`## Requirements`, '', ...spec.requirements.map(r => `- ${r.description}`), '');
  }
  
  if (spec.tasks && spec.tasks.length > 0) {
    lines.push(`## Tasks`, '', ...spec.tasks.map(t => `- [${t.status === 'done' ? 'x' : ' '}] ${t.description}`), '');
  }
  
  if (spec.metadata?.notes) {
    lines.push(`## Notes`, '', spec.metadata.notes, '');
  }
  
  return lines.join('\n');
}

/**
 * Generate proposal template
 */
export function generateProposalTemplate(title: string, description: string): string {
  return `# Proposal: ${title}

## Problem

What problem are we solving?

## Solution

${description}

## Impact

What will this change accomplish?

## Risks

What could go wrong?

## Alternatives

What other approaches were considered?

---

*Generated by SpecVibe*
`;
}

/**
 * Generate design document template
 */
export function generateDesignTemplate(title: string): string {
  return `# Design: ${title}

## Architecture

High-level approach

## Technical Details

Implementation specifics

## API Changes

Any API modifications

## Data Model

Database/schema changes

## Security

Security considerations

## Testing

Test plan

---

*Generated by SpecVibe*
`;
}

/**
 * Generate tasks template
 */
export function generateTasksTemplate(spec: Spec): string {
  const lines: string[] = [
    `# Tasks: ${spec.title}`,
    '',
    '## Implementation Checklist',
    '',
  ];
  
  // Group tasks by requirement
  const requirementTasks = new Map<string, Task[]>();
  const uncategorizedTasks: Task[] = [];
  
  for (const task of spec.tasks || []) {
    if (task.requirementIds && task.requirementIds.length > 0) {
      for (const reqId of task.requirementIds) {
        if (!requirementTasks.has(reqId)) {
          requirementTasks.set(reqId, []);
        }
        requirementTasks.get(reqId)!.push(task);
      }
    } else {
      uncategorizedTasks.push(task);
    }
  }
  
  // Output tasks grouped by requirement
  for (const [reqId, tasks] of requirementTasks) {
    const requirement = spec.requirements?.find(r => r.id === reqId);
    lines.push(`### ${requirement?.description || reqId}`, '');
    for (const task of tasks) {
      lines.push(`- [${task.status === 'done' ? 'x' : ' '}] ${task.description}`);
    }
    lines.push('');
  }
  
  // Uncategorized tasks
  if (uncategorizedTasks.length > 0) {
    lines.push('### General', '');
    for (const task of uncategorizedTasks) {
      lines.push(`- [${task.status === 'done' ? 'x' : ' '}] ${task.description}`);
    }
    lines.push('');
  }
  
  lines.push('---', '', '*Generated by SpecVibe*');
  
  return lines.join('\n');
}

/**
 * Create a requirement
 */
export function createRequirement(
  description: string,
  type: Requirement['type'] = 'functional',
  priority: Requirement['priority'] = 'must'
): Requirement {
  return {
    id: `req-${Date.now()}`,
    description,
    type,
    priority,
    satisfied: false,
  };
}

/**
 * Create a task
 */
export function createTask(
  description: string,
  requirementIds?: string[],
  estimate?: string
): Task {
  return {
    id: `task-${Date.now()}`,
    description,
    status: 'todo',
    requirementIds,
    estimate,
  };
}
